spring:
  application:
    name: java-coding-challenge

  datasource:
    url: jdbc:h2:mem:fxrateservice
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.crewmeister.cmcodingchallenge: DEBUG
  file:
    name: logs/java-coding-challenge.log

bundesbank:
  api:
    url: https://api.statistiken.bundesbank.de/rest
    endpoints:
      rates: /data/BBEX3/
      currencies: /metadata/codelist/BBK/CL_BBK_STD_CURRENCY
    timeout:
      connect: 5000
      read: 10000
    retry:
      attempts: 3
      delay: 2000
    default-detail: dataonly

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
info:
  app:
    name: FX Rate Service
    description: Provides FX currency data and conversions from Bundesbank
    version: 1.0.0

scheduling:
  enabled: true